// POST /api/unsubscribe
// Verifies the HMAC token from the unsubscribe link and marks the enrollment
// as unsubscribed in the database.
//
// Token is generated by generateUnsubscribeToken() in lib/sendgrid.ts using
// HMAC-SHA256 over the email address with UNSUBSCRIBE_SECRET as the key.
// This prevents anyone from unsubscribing an address they don't control.

import { NextResponse } from 'next/server'
import { generateUnsubscribeToken } from '@/lib/sendgrid'

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { email, token } = body

    // ── Validate inputs ──────────────────────────────────────────────────────
    if (!email || typeof email !== 'string') {
      return NextResponse.json({ error: 'Missing email' }, { status: 400 })
    }
    if (!token || typeof token !== 'string') {
      return NextResponse.json({ error: 'Missing token' }, { status: 400 })
    }

    // ── Verify HMAC token ────────────────────────────────────────────────────
    // Recompute the expected token for this email and compare.
    // Uses timing-safe comparison to prevent timing attacks.
    const expectedToken = generateUnsubscribeToken(email)
    if (!timingSafeEqual(token, expectedToken)) {
      console.warn('[unsubscribe] Invalid token for email:', email)
      return NextResponse.json({ error: 'Invalid or expired unsubscribe link.' }, { status: 403 })
    }

    // ── Update DB ────────────────────────────────────────────────────────────
    // Uncomment when DB is connected:
    //
    // import mysql from 'mysql2/promise'
    // const conn = await mysql.createConnection(process.env.DATABASE_URL!)
    //
    // const [rows] = await conn.execute(
    //   `SELECT id, unsubscribed_at FROM refi_enrollments
    //    WHERE email = ? AND unsubscribed_at IS NULL
    //    LIMIT 1`,
    //   [email.toLowerCase().trim()]
    // )
    //
    // if (!rows.length) {
    //   await conn.end()
    //   return NextResponse.json({ ok: true, alreadyUnsubscribed: true })
    // }
    //
    // await conn.execute(
    //   `UPDATE refi_enrollments SET unsubscribed_at = NOW() WHERE email = ?`,
    //   [email.toLowerCase().trim()]
    // )
    // await conn.end()

    // ── Stub response (remove when DB is connected) ──────────────────────────
    const alreadyUnsubscribed = false  // stub — DB query will determine this

    console.log('[unsubscribe] Unsubscribed (stub):', email)
    return NextResponse.json({ ok: true, alreadyUnsubscribed })

  } catch (err) {
    console.error('[unsubscribe] Error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// ── Timing-safe string comparison ───────────────────────────────────────────
// Prevents attackers from using response time to guess valid tokens character
// by character. Falls back gracefully if strings differ in length.

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let mismatch = 0
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i)
  }
  return mismatch === 0
}
